language: php
php:
- '5.5'
- '5.6'
- '7.0'
- hhvm
- nightly
install: composer install --dev
env:
  global:
  - secure: FVLSHe0WnE9VYVIl7KEpzxQ8zMh6iB9RPtDykDi+KuzdhSyJJ0L105uG/3RddtAB9punXafWFmfCMan8BxikkDdMtl6mCJXjeQA+kCsK2B9lhdf+h+NW4RsE4SsI3NWR/f4H4stdDJ/gUy/GcC1QXF8msGrIqna8qrhS5ys1+nQPza7qy5IJn9BQP9ORMnvAUje7bgWuPox9lCDbbjs6yzgNhF9GwHMSXBfG7g0mAPEMLbDaw/ZqyzSs/gV609kIKqwVR/rHGSAnKQVuNojuPhf6H5Cdg2SbxkZ5NfBUyJRsTEGmyRauZRtQjLKSDG9MyR7hdzCpXabyIvVz6azH+tdTLUMJdoMXh6mhOygENHMlIihRlwt2SFQT+f4kFh8hPb2wZGlgwX7yDmd4GMfK3yHxCQc5YGZCYlzUPhhCL/B4gGt2gxxOs3as7TLuCB0Frf/77kyCqNVl9LAJ+HvrH/+HnKPjY7C0cOST/rgWJ/ftI1gH9rZ/q433tvN/cEB89dfzFCH/rtFaZoiW7GbIr7xakTq54ncbEpLt7KTJqPBAu/55Hq15z5Q53KOj0q9mF/nyxsUzHVdnnPIEL219mzdbfOkomGcUtlJDYJHYZOVSxZA5NzEF+vzazAJkOFOuieWxOfJ1bLEWi5CeyoKL+jbM8bTnsRWLOUsGKd84L8I=
  - secure: nahNQUhB+/06NCpTc9lb9USxM+cYXPPhZb7BoPtmn9YfAgSSj23hXy5K79MtdT6cVShCQe4DdmCmfPfIBm9LS3YTaj7DJ8RLQJ3zVgZbB23OywT1JdQbi5f2AQlhNZ6tFzF/5pkaMqsc+50gRIN90GVLQTvDWGqUAZuuHk1GV0jhV+tT1/mzh6i0yJ4fyg5wLAu5Fqqy70wff1g9QY4URpghurHPC3/l5VHoGa4OjYZyjjKwYJ7sUEu9cxQwdWQGiK0Y4UGfav8Ju2nGZAc4DjoVH1d3tkHLcaNQQMDUTCZD3w0ltAaEWtdB1lMeO0Bgn+4Y+ksVTtGjrIHPkvhtWQDk7B5EGq0lHBH8rHuQXhuciDs7ArAK7VBemiqdZEFqAYwjsUtWutzLonpX4/imVN5MECCiTJlZTxx7XYmpxixUo7Kep+zj9HLm25W7vxhcQyfxp1aAdg/iUO5DLWBuSA72huG/CU1qW/ikC6sHS8QLkfAw5NxjsnWYSfkYjfinRtB/X2MEC8+bcR5JueD0eBtf0VWr7JDJjGFWGxR7OCZFylNq67Oxw/+sQHJokfwJUY/DSIknXK/BjaxSrL3miwBRwfjfcPYXfxSQS26aDOryovZiNbQVVTA5SP7FMTLo1oLgEseftP6XlzSDtb6ZCkN0qEe8mWGt9C8hm2lMFX8=
