language: php
php:
- '5.5'
- '5.6'
- '7.0'
- hhvm
- nightly
install: composer install --dev
env:
  global:
  - secure: l6xtovRwmQpsm1n5pxy+tveIEBrKH/RLu0xF+4B9OAgxYqxL4pJK5ucff9nwnPmTxcwgu3m4/6QSKV8/fHCP3VniYHo52H27U2V2RTyKI5nl/3IcOZrAb7s00wXLL0p5wxEIIPuPajB3JOow43+OK725YQSC63MijkhoJplsco2FTslObYvCve4oLt5wgLC30BoWruVEtYV1f3RAdLAHIzgUqphxuq+1f7786AxtyfbmjTYu43BhK7ilOrewv+wynbGh02ty2cE51dwiU9U/El1QTQ5V3ZNtiN357eV3iPIWsIBw6spvGMWj+wkNeIErBGsvcoYAwItA7ZV2WFOxUQsZNCN2XoOT1rqjhNS4tlzAb4KQa/aHqaG6ah0ssp4nXjERYg49a27wgwdlV8jzIXw45cQ9w0K3JKicfLUho5grNKwzCWVgteySwQFI24Lq340NOJrTG6aPR4FYlfC7VEvVvGotlMTsd+FJNLtiQV4pR5HwFR2oS3CF8tKHbO3hxGG5x0/qSyXIX/Ka/w+mlcSYz6x8evZoaKzsNp2XBha3OLkN7YhsDYTGzvcQW7dMPExcpb4mUCZYEAa4tvIgeT+pXenKpgXatHyA0xy1GSMTM95ISAGyAOeGE6JDb91vQSGcxDZqZm8wBuI+7LwQrbn7runjOuR6y1oDn+1OEwA=
  - secure: pAjLxhYDZ15u17T4eJzm4KcxeGkNVqiGb5yhOL8XBhpyhwaVqfm88/Oio4iWvHQfWjImt6ZkCz6fUeqLlgkljlugN/D8Yzm+nhwR2gwoVuUBq229IAzqX49kyz+jkQDIAGF/ZFjzk0UCoCvuHBRXD8C112VCEmupkPbR9Bs2WEnv107RllYD9HaG1XhbrxLAmQEWxlCjgw2F8k5PEP7qrDWtFmOqT01ddqMVZ6UZLES4hsnvqVSB94ZchoaSyNRkG4vk7Hlw0/i43JS29Jw97R42PNEw19XgzvHz4FwTuCK0lt4dm/WS4lYPSPPuKUfSk0fdCj0v5WGA+W1/hAbVFvwIO2mBa7vRijuP8DFQvZEfd7pbITVg3um8IC8FMPyDZIpv1G5engB5nJ8J4xUlpB/XQfSGczqkE3rowClSJyEQ0FGef1bdQJE972gceZAOlwtiX+GHIBQjtEzWAUX0A5npNfx4lrsDKSvtI/kWgdLejGp1MqfVJFr6mqLOtFBNEqRVa3MrBVkY97Pp0pJB2QDJSxlpNx2E+rndlmFQkignzWwSKHYY1LfmhPf8h3mKsXizmuwyAUruIsf8uumslxOnRdYwtlwiHsqE7/x1xRn58MLPalt5+hzZbZj7r1/UMh2zZKyUUdm3qLVgK7HJ55MxzAsSTu5uE4pqoJF/6Tw=
